# Generated by Django 5.1.6 on 2025-04-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemandeRecuperationDiplome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=100)),
                ("nom", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("date_naissance", models.DateField()),
                ("adresse", models.CharField(max_length=255)),
                ("numero_table", models.CharField(max_length=50)),
                ("annee_bac", models.IntegerField()),
                ("lettre_demande", models.FileField(upload_to="documents/")),
                ("attestation_diplome", models.FileField(upload_to="documents/")),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
