# Generated by Django 5.1.6 on 2025-04-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demarche", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecuperationDiplome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=100)),
                ("nom", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("date_naissance", models.DateField()),
                ("adresse", models.CharField(max_length=255)),
                ("numero_table", models.IntegerField()),
                ("annee_bac", models.IntegerField()),
                ("lettre_demande", models.FileField(upload_to="lettres_demande/")),
                (
                    "attestation_diplome",
                    models.FileField(upload_to="attestations_diplome/"),
                ),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="DemandeRecuperationDiplome",
        ),
    ]
