# Generated by Django 5.0.7 on 2025-04-30 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demarche", "0002_recuperationdiplome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recuperationdiplome",
            name="date_naissance",
            field=models.DateField(default=datetime.date(2003, 2, 15)),
        ),
    ]
